# Generated by Django 5.1.2 on 2024-10-24 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['name'], 'verbose_name': 'Kích cỡ', 'verbose_name_plural': 'Kích cỡ'},
        ),
    ]
