# Generated by Django 5.1.2 on 2024-10-29 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Thương hiệu', 'verbose_name_plural': 'Thương hiệu'},
        ),
    ]
