# Generated by Django 5.1.2 on 2024-10-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0002_alter_brand_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_color',
            field=models.CharField(default='000000', max_length=6, verbose_name='Mã màu (hex)'),
        ),
    ]
