# Generated by Django 5.1.2 on 2024-10-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0003_color_hex_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='hex_color',
        ),
        migrations.AddField(
            model_name='color',
            name='hex_color_1',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Mã màu 1'),
        ),
        migrations.AddField(
            model_name='color',
            name='hex_color_2',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Mã màu 2'),
        ),
    ]
