# Generated by Django 5.1.2 on 2024-10-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0004_remove_color_hex_color_color_hex_color_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Màu sắc', 'verbose_name_plural': 'Màu sắc'},
        ),
    ]
