# Generated by Django 5.1.2 on 2024-10-29 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shoe_rating_alter_review_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='rating',
        ),
    ]
